base_url = "https://miguelpimentel.do/zola-docs/"
title = "Zola Docs"
description = "An easy way to document your projects."
compile_sass = true
build_search_index = true

[markdown]
highlight_code = true
highlight_theme = "zenburn"

[extra]
logo = "https://easydocs.codeandmedia.com/logo.svg"
release = "https://api.github.com/repos/getzola/zola/releases/latest"
favicon = "https://www.getzola.org/favicon.ico"
easydocs_logo_always_clickable = false
easydocs_uglyurls = false
easydocs_heading_threshold = 5
