name = "Zola Docs"
description = "An easy way to create docs for your project."
license = "MIT"
homepage = "https://github.com/semanticdata/zola-docs"
min_version = "0.17.2"
demo = "https://semanticdata.github.io/zola-docs"

[author]
name = "Miguel Pimentel"
homepage = "https://miguelpimentel.do"
